import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Legal & Disclaimer | WHALEZ-AI",
  description:
    "Legal disclaimers, terms of use, and privacy information for WHALEZ-AI and DeltaAlpha-TradePro platforms.",
}

export default function LegalPage() {
  return (
    <>
      <Navigation />
      <main className="pt-16">
        <section className="py-24 md:py-32">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl">
              <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold tracking-tight text-foreground text-balance">
                Legal & Disclaimer
              </h1>
              <p className="mt-6 text-muted-foreground leading-relaxed">
                Please read the following information carefully before using WHALEZ-AI or DeltaAlpha-TradePro.
              </p>
            </div>

            <div className="mt-16 max-w-3xl space-y-12">
              <div>
                <h2 className="text-xl font-medium text-foreground">No Financial Advice</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    WHALEZ-AI and DeltaAlpha-TradePro do not provide financial advice, investment recommendations, or
                    personalized guidance of any kind. All content, signals, analysis, and outputs generated by our
                    platforms are strictly informational and educational in nature.
                  </p>
                  <p>
                    Nothing on our platforms should be construed as a recommendation to buy, sell, or hold any financial
                    instrument, security, or digital asset. Users are solely responsible for their own financial
                    decisions and should consult with qualified financial advisors before making any investment choices.
                  </p>
                </div>
              </div>

              <div>
                <h2 className="text-xl font-medium text-foreground">No Investment Guarantees</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    We make no representations or guarantees regarding the accuracy, completeness, timeliness, or
                    profitability of any information provided through our platforms. Past performance of any strategy,
                    signal, or analysis does not guarantee future results.
                  </p>
                  <p>
                    Financial markets involve substantial risk of loss. You could lose some or all of your capital.
                    WHALEZ-AI accepts no liability for any losses incurred as a result of using our platforms or acting
                    on information derived from them.
                  </p>
                </div>
              </div>

              <div>
                <h2 className="text-xl font-medium text-foreground">Experimental Beta Platform</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>WHALEZ-AI and DeltaAlpha-TradePro are currently in a beta development phase. This means:</p>
                  <ul className="space-y-2 ml-4">
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      Features may be incomplete, unstable, or subject to change without notice
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      Data and analysis may contain errors or inaccuracies
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      Service availability is not guaranteed
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      Access may be modified, limited, or terminated at our discretion
                    </li>
                  </ul>
                </div>
              </div>

              <div>
                <h2 className="text-xl font-medium text-foreground">User Responsibility</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>By using our platforms, you acknowledge that:</p>
                  <ul className="space-y-2 ml-4">
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      You are solely responsible for evaluating the merit and risks of any information
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      You will not rely solely on our outputs for financial decisions
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      You understand the experimental nature of this platform
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-primary mt-1.5">•</span>
                      You accept all risks associated with participation in financial markets
                    </li>
                  </ul>
                </div>
              </div>

              <div id="privacy">
                <h2 className="text-xl font-medium text-foreground">Privacy</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    We collect minimal information necessary to operate our beta program, including contact information
                    provided during registration. We do not sell personal data to third parties.
                  </p>
                  <p>
                    Usage data may be collected to improve our platforms and understand how users interact with our
                    tools. This data is used internally for product development purposes only.
                  </p>
                  <p>For questions about data handling, please contact us through our beta access application.</p>
                </div>
              </div>

              <div>
                <h2 className="text-xl font-medium text-foreground">Intellectual Property</h2>
                <div className="mt-4 space-y-4 text-muted-foreground leading-relaxed">
                  <p>
                    All content, design, code, algorithms, and systems comprising WHALEZ-AI and DeltaAlpha-TradePro are
                    proprietary and protected by applicable intellectual property laws. Unauthorized reproduction,
                    distribution, or reverse engineering is prohibited.
                  </p>
                </div>
              </div>

              <div className="p-6 rounded-lg border border-border bg-card">
                <p className="text-sm text-muted-foreground leading-relaxed">
                  <strong className="text-foreground">Last Updated:</strong> December 2024
                </p>
                <p className="mt-4 text-sm text-muted-foreground leading-relaxed">
                  These terms may be updated periodically. Continued use of our platforms constitutes acceptance of any
                  modifications. If you do not agree with these terms, please discontinue use of WHALEZ-AI and
                  DeltaAlpha-TradePro.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
